blank_issues_enabled: false
contact_links:
  - name: Discordサーバー
    url: https://discord.gg/p3rUZqS2QN
    about: 公式サーバーはこちらから
  - name: Discordサポートサーバー
    url: https://discord.gg/zaQnvmrp76
    about: サポートサーバーはこちらから
